# Generated by Django 4.2.18 on 2025-11-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiontemplate',
            name='dashboard_id',
        ),
        migrations.RemoveField(
            model_name='permissiontemplate',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='permissiontemplate',
            name='sub_department_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subdepartment'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionTemplate',
        ),
    ]
