# Generated by Django 4.2.18 on 2025-11-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_permissiontemplate_permission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
