# Generated by Django 4.2.18 on 2025-11-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_permission_permission_unique_permission_combination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
