# Generated by Django 4.2.18 on 2025-11-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_permission_permission_unique_permission_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
